### ISSUE TITLE
Evaluator output is messed up

### ISSUE THREAD

**Issue by nikoliazekter** [chainer/chainerrl#139]
The columns in evaluator output are misaligned as demonstrated here https://github.com/chainer/chainerrl/issues/138#issuecomment-323265078

`print('\t'.join(str(x) for x in values), file=f)` should be replaced with code that uses [alignment specifiers](https://docs.python.org/2/library/string.html#format-specification-mini-language).

**Comment by muupan** [comment]
Since `scores.txt` is just a TSV file, you can pretty print it by `column -t scores.txt` or something.
