### ISSUE TITLE
Argument name inconsistent with the interface

### ISSUE THREAD

**Issue by lyx-x** [chainer/chainerrl#229]
I noticed that methods in some algorithms have different argument name from the one defined in the Agent base-class. Since I prefer using named parameters in my code (too many parameters in RL), this is a little bit annoying. I am going to create a pull request and align every arguments with the one defined in Agent base-class. Is there any suggestions and recommendations on that before I proceed?

https://github.com/chainer/chainerrl/blob/a363e0cabb77bd1716ccd1daa559234adaf69982/chainerrl/agents/dqn.py#L373

https://github.com/chainer/chainerrl/blob/a363e0cabb77bd1716ccd1daa559234adaf69982/chainerrl/agent.py#L45

**Comment by muupan** [comment]
Good point. I agree that `state` should be `obs`. Feel free to send a PR for it.
