### ISSUE TITLE
off policy updates

### ISSUE THREAD

**Issue by Homagn** [chainer/chainerrl#254]
looking at the code, I cannot convince myself how to use this for off-policy learners

what if instead of agent.act_and_train() +agent.stop_episode_and_train() (in outer loop) I do this

agent.update(experiences)
agent.synchronize_target_network()
(both in the inner loop)

would that work? Or does the agent.act_and_train() must be used always

**Comment by muupan** [comment]
DQN is already off-policy in that it uses a given explorer to choose actions, but if you need to train it with offline experiences, I guess agent.update and agent.synchronize_target_network will work (not tested).

**Comment by Homagn** [comment]
Thanks for the fast reply !
For the given circumstances in my problem, unfortunately I cannot use agent.act_and_train method as is shown in most examples with gym environments

So are you saying if I collect all the experiences and just do an agent.update(experiences) that would still work?

**Comment by muupan** [comment]
> So are you saying if I collect all the experiences and just do an agent.update(experiences) that would still work?

Yes, I think that should work if you call agent.synchronize_target_network() at an appropriate interval, but I've never tried that way of training. I would appreciate it if you report whether it works.
