### ISSUE TITLE
Add tutorials like chainer doc

### ISSUE THREAD

**Issue by arisliang** [chainer/chainerrl#265]
Chainer documentation has Guide and Neural Net Examples that is quite friendly to beginners, with its slower pace, and not as overwhelming as the reference and source code for starter. It'll be quite cool to do the same for Chainer RL as well.

**Comment by arisliang** [comment]
quickstart guide is good (https://github.com/chainer/chainerrl/blob/master/examples/quickstart/quickstart.ipynb). Maybe can fit that shoe, maybe can be moved to the doc site so it's easier to access.

**Comment by muupan** [comment]
The quickstart guide is already linked from the documents. http://chainerrl.readthedocs.io/en/latest/index.html

I agree it is better to add more tutorials, especially for other algorithms than DQN.

**Comment by arisliang** [comment]
`The quickstart guide is already linked from the documents. ` Oh there, I missed that, thanks for the link. 

Still the tutorial style feels better to me, it's like a story telling, where notebook is more like presenting the code with some comments.
