### ISSUE TITLE
Replicate Prioritized Experience Replay's reported performance improvements

### ISSUE THREAD

**Issue by muupan** [chainer/chainerrl#278]
Missing details
- "all weights w_i were scaled so that max_i w_i = 1". Is max_i w_i computed over a minibatch or the whole buffer?
- What is the value of epsilon that is added to absolute TD errors?

**Comment by muupan** [comment]
I asked the author via email and confirmed
- max_i w_i is computed over a minibatch
- epsilon=0.01

**Comment by muupan** [comment]
breakout: :ok:
![image](https://user-images.githubusercontent.com/815970/46408788-44c5f280-c74e-11e8-8273-0c5c06792a08.png)
<img width="201" alt="screen shot 2018-10-03 at 20 52 05" src="https://user-images.githubusercontent.com/815970/46412693-31208900-c75a-11e8-94c3-8e547a69d773.png">
<img width="397" alt="screen shot 2018-10-03 at 22 19 42" src="https://user-images.githubusercontent.com/815970/46412795-76dd5180-c75a-11e8-8c14-bf3e845e584e.png">

**Comment by muupan** [comment]
space invaders: :ok:
![image](https://user-images.githubusercontent.com/815970/46412839-97a5a700-c75a-11e8-829d-829698fb046d.png)
<img width="199" alt="screen shot 2018-10-03 at 22 21 10" src="https://user-images.githubusercontent.com/815970/46412870-aa1fe080-c75a-11e8-9895-3155290f80a2.png">

**Comment by muupan** [comment]
asterix: :ok:
![image](https://user-images.githubusercontent.com/815970/46413195-61b4f280-c75b-11e8-9f27-2e15d13a4a52.png)
<img width="209" alt="screen shot 2018-10-03 at 22 26 39" src="https://user-images.githubusercontent.com/815970/46413224-6da0b480-c75b-11e8-8e2e-e9993a6faefb.png">

**Comment by muupan** [comment]
qbert: :ok:
![image](https://user-images.githubusercontent.com/815970/46413297-8e690a00-c75b-11e8-81fa-021adf92c7a2.png)
<img width="204" alt="screen shot 2018-10-03 at 22 27 55" src="https://user-images.githubusercontent.com/815970/46413322-9cb72600-c75b-11e8-81a9-904080a7a500.png">

**Comment by muupan** [comment]
similar results: breakout, space invaders, asterix, qbert
a bit worse than the paper: seaquest, beam rider

They seem to use 500,000 frames instead of 108,000 frames for evaluation (B.2.3 of http://arxiv.org/abs/1511.05952), so trying 500,000 frames may fill the gap.

**Comment by prabhatnagarajan** [comment]
Tested 7 games: Breakout, Space Invaders, Seaquest, Asterix, Beam Rider, Qbert.

Results:

Breakout: 🆗
Space Invaders: 🆗
Seaquest: worse
Beam Rider: slightly worse
Asterix:🆗
Qbert: 🆗

@muupan suggested that it appears that the evaluations used in the paper permitted longer episodes during evaluations, potentially explaining our slightly worse performance in 2 domains.
