### ISSUE TITLE
Abstract method is not overridden in some of the gaussian policies

### ISSUE THREAD

**Issue by uidilr** [chainer/chainerrl#281]
I made PR #280 that update Policy class to inherit ABCMeta.
From Travis-CI log, it turned out that two gaussian policy classes,  https://github.com/chainer/chainerrl/blob/2be8d0b64140edffb0c9ac32b78f883786299f10/chainerrl/policies/gaussian_policy.py#L132 
and 
https://github.com/chainer/chainerrl/blob/2be8d0b64140edffb0c9ac32b78f883786299f10/chainerrl/policies/gaussian_policy.py#L203
does not override abstract method of gaussian policy. 

https://github.com/chainer/chainerrl/blob/2be8d0b64140edffb0c9ac32b78f883786299f10/chainerrl/policies/gaussian_policy.py#L27-L37  

Does function `compute_mean_and_var` has to be the abstract method?

**Comment by uidilr** [comment]
I thought about two candidates of solutions to this issue.

####  1.  Implement method `compute_mean_and_var` for these two classes.
- Advantage
  - It follows the principle of objected-oriented.
- Disadvantage
  - It is redundant to implement unused method.

#### 2.  Inherit `Policy` class instead of `GaussianPolicy` 
- Advantage
  -  Less modification
- Disadvantage 
  - It is inconsistent to inherit `Policy` instead of `GaussianPolicy`, when the sub-class's name includes "GaussianPolicy". It is confusing and someone may try to call `compute_mean_and_var` of these sub-class and get error. 

I think that the first one is better.   
What do you think?

**Comment by muupan** [comment]
Sorry for my late response. This needs to be fixed.

I'm for removing `GaussianPolicy` interface completely and inheriting `Policy` instead because `GaussianPolicy` does not help simplify implementing a Gaussian policy.

**Comment by toslunar** [comment]
Closed by #305.
