### ISSUE TITLE
train_A3C_gym 

### ISSUE THREAD

**Issue by xylee95** [chainer/chainerrl#296]
Hello,

I am trying to run the train_A3C_gym.py in a cluster and I'm wondering if there are any arguments that I can pass in to limit the number of cores used by the multiprocessing? 

It seems like I can only control the number of workers but not the number of cores used by the workers?

**Comment by muupan** [comment]
ChainerRL does not provide such an option.

This might help: https://unix.stackexchange.com/questions/23106/how-to-limit-a-process-to-one-cpu-core-in-linux

**Comment by xylee95** [comment]
Thank you, I found a solution!
