### ISSUE TITLE
Documentation: DoubleDQN is missing

### ISSUE THREAD

**Issue by alexberd** [chainer/chainerrl#297]
Page 23 of documentation says "DoubleDQN (class in chainerrl.agents), 9" but there is no DoubleDQN documentation!

**Comment by muupan** [comment]
> Page 23 of documentation

Which page do you mean? Can you give me a link to it?

It is true that DoubleDQN's docstring is scarce. It would be better to state there that it is the same as DQN except target value calculation.

**Comment by alexberd** [comment]
Hi muupan, I am sorry for my late reply.

ChainerRL Documentation
[https://media.readthedocs.org/pdf/chainerrl/latest/chainerrl.pdf]

1. class chainerrl.agents.DQN is duplicated pages 10 and 11.
2. class chainerrl.agents.DoubleDQN is at page 10 and not at page 9 as Index says at page 23

Hope these are useful to update your documentation.

Best,
Alex

**Comment by muupan** [comment]
Sorry for the late response. You are right, the current PDF looks weird. Thank you for pointing it out.
