### ISSUE TITLE
train_experiment_async

### ISSUE THREAD

**Issue by xylee95** [chainer/chainerrl#300]
Does the experiments.train_agent_async work with any kind of agent?

I see that in the examples, it was used for training A3C but I would like to know if my agent is a PPO or DQN, would train_agent_async framework still work with respect to the way DQN or PPO updates it's weights?

**Comment by muupan** [comment]
No, currently only a subset of the agents like A3C, ACER and NSQ support async training. They implement chainerrl.agent.AsyncAgent to indicate which data need be shared across processes.

I think it is possible to extend DQN or PPO to support async training as well, but I have no idea how well they actually work.
