### ISSUE TITLE
unable to run examples

### ISSUE THREAD

**Issue by windmaple** [chainer/chainerrl#331]
Did a fresh install of chianerrl and cupy, but was not able to run the example at all. Tried both python2/3.

(ml) weiwe@weiwe2:~/chainerrl/examples/gym$ python train_reinforce_gym.py
/usr/local//home/weiwe/ml/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train_reinforce_gym.py", line 149, in <module>
    main()
  File "train_reinforce_gym.py", line 82, in main
    train_env = make_env(test=False)
  File "train_reinforce_gym.py", line 71, in make_env
    env = chainerrl.wrappers.CastObservationToFloat32(env)
AttributeError: 'module' object has no attribute 'wrappers'

**Comment by muupan** [comment]
This is due to the recent API change of ChainerRL, merged to the master branch but not yet released at PyPI. You can run the examples by using the latest master of `chainerrl` on github, e.g, `pip install git+git://github.com/chainer/chainerrl.git`.

**Comment by muupan** [comment]
Released chainerrl==0.5.0 which should resolve this issue.
