### ISSUE TITLE
Make new gym/environment

### ISSUE THREAD

**Issue by saj1919** [chainer/chainerrl#338]
Is there a tutorial/code on "how to make new/custom environment" like gym environment available in openai ??

Can someone point me to the same ... not able to find the same in documentation.

**Comment by muupan** [comment]
Currently there's no such tutorial in ChainerRL, but it's not hard to implement your own gym environment. You can check how gym envs are implemented: https://github.com/openai/gym/blob/master/gym/envs/classic_control/mountain_car.py
