### ISSUE TITLE
Invalid operation in: Concat (Forward)

### ISSUE THREAD

**Issue by biggzlar** [chainer/chainerrl#364]
https://github.com/chainer/chainerrl/blob/e04c28373702872a7581bcad66a993f8258d930c/chainerrl/q_functions/state_action_q_functions.py#L68

Not sure how this is supposed to work, but it doesn't. Apparently this tries to concatenate an observation and an action - I would argue that in almost all cases those two have different dimensions.

**Comment by muupan** [comment]
Right, it is supposed to work only when state.ndim == action.ndim == 2. When they have different number of dimensions, e.g., states are 2D images, it won't work.

**Comment by biggzlar** [comment]
I see, thank you for your response. Alternatively I guess one could always append a tiled array of the action...
