### ISSUE TITLE
PPO agent does not save `obs_normalizer` attribute

### ISSUE THREAD

**Issue by oribarel** [chainer/chainerrl#376]
Current implementation of the PPO agent does not save the `obs_normalizer` attribute (See https://github.com/chainer/chainerrl/blob/master/chainerrl/agents/ppo.py#L80).
I believe this is a bug since when loading the agent, the mean and variance for normalizing do not exist.
Compare with the TRPO implementation (https://github.com/chainer/chainerrl/blob/master/chainerrl/agents/trpo.py#L161)

**Comment by muupan** [comment]
You are right. Thank you for pointing it out!

**Comment by oribarel** [comment]
Thanks for the quick reply. Until it is being fixed, a sufficient workaround would be adding this attribute to the static attribute `saved_attributes` manually, isn't it? Should I change something else?
