### ISSUE TITLE
Combination of DDPG & PrioritizedReplayBuffer fails

### ISSUE THREAD

**Issue by minokunn15** [chainer/chainerrl#382]
The failure happens at sample in prioritized.py.
The following is the error message.

`/chainerrl/misc/prioritized.py", line 114, in sample
    not self.flag_wait_priority)
`

**Comment by muupan** [comment]
This combination is not currently supported. Is there any reference on how priorities should be assigned for DDPG?

**Comment by minokunn15** [comment]
I'm sorry I don't know it. 
The follow is the reference. 
https://github.com/cardwing/Codes-for-RL-PER

**Comment by prabhatnagarajan** [comment]
Thank you for the reference to DDPG with Prioritized Replay. As mentioned, it's currently not supported. 
Consult the DQN agent for a reference on how DDPG with Prioritized Replay may be implemented.
