### ISSUE TITLE
NonbiasWeightDecay does not contain a `timing` attribute

### ISSUE THREAD

**Issue by oribarel** [chainer/chainerrl#388]
The hook function `NonbiasWeightDecay` does not contain a `timing` attribute, and hence the `add_hook` function raises a warning when using that hook. Can you please explain what is the more reasonable choice for `timing` in this case, when choosing between `pre` or `post`, and why?

**Comment by muupan** [comment]
It must be `pre` because it should work as `chainer.optimizer_hooks.WeightDecay` does. I'll fix this issue soon.
