### ISSUE TITLE
Add support for recurrent PPO

### ISSUE THREAD

**Issue by oribarel** [chainer/chainerrl#397]
Hi,

Do you have any plans to add support for recurrent models in the PPO agent?
If not, what is the main effort that should be done in order to make it work?

**Comment by muupan** [comment]
It is on our to-do list. The main effort will be write a recurrent version of update iterations that batch episodes in memory, not transitions, and evaluate them sequentially.

**Comment by muupan** [comment]
I'm now working on this.

**Comment by muupan** [comment]
It's not merge yet, but it works as it is. https://github.com/chainer/chainerrl/pull/431
