### ISSUE TITLE
NVRTC_ERROR_COMPILATION (6)

### ISSUE THREAD

**Issue by ling-pan** [chainer/chainerrl#413]
Hi, I am wondering why running with chainerrl encounters the following error:

> cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

The detail information of the error is as below:

> File "cupy/core/core.pyx", line 1178, in cupy.core.core.ndarray.setitem
> File "cupy/core/_routines_indexing.pyx", line 49, in cupy.core._routines_indexing._ndarray_setitem
> File "cupy/core/_routines_indexing.pyx", line 739, in cupy.core._routines_indexing._scatter_op
> File "cupy/core/_kernel.pyx", line 851, in cupy.core._kernel.ufunc.call
> File "cupy/core/_kernel.pyx", line 863, in cupy.core._kernel.ufunc._get_ufunc_kernel
> File "cupy/core/_kernel.pyx", line 625, in cupy.core._kernel._get_ufunc_kernel
> File "cupy/core/_kernel.pyx", line 59, in cupy.core._kernel._get_simple_elementwise_kernel
> File "cupy/core/carray.pxi", line 164, in cupy.core.core.compile_with_cache
> File "******/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 165, in compile_with_cache
> ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
> File "******/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 81, in compile_using_nvrtc
> ptx = prog.compile(options)
> File "******/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 246, in compile
> raise CompileException(log, self.src, self.name, options)
> cupy.cuda.compiler.CompileException: ******/anaconda3/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
> detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]"
> /tmp/******.cubin.cu(11): here
> 
> /tmp/******.cubin.cu(14): error: no suitable conversion function from "const in0_type" to "out0_type" exists
> 
> 1 error detected in the compilation of "/tmp/******.cubin.cu".

My environment information are as below:

> Chainer: 6.0.0b3
> NumPy: 1.14.3
> CuPy:
>   CuPy Version          : 6.0.0b3
>   CUDA Root             : /usr/local/cuda
>   CUDA Build Version    : 8000
>   CUDA Driver Version   : 10010
>   CUDA Runtime Version  : 8000
>   cuDNN Build Version   : 7102
>   cuDNN Version         : 7102
>   NCCL Build Version    : 2213
>   NCCL Runtime Version  : (unknown)
> iDeep: Not Available

I have tried setting the path for cuda in ~/.bashrc, but it does not work.

**Comment by muupan** [comment]
I have never seen such an error. Do chainer and cupy work fine in your environment?

**Comment by kmaehashi** [comment]
I think this issue is not related to ChianerRL.
Let's continue discussion here: https://github.com/cupy/cupy/issues/2100
