### ISSUE TITLE
Unable to load two models in the same script

### ISSUE THREAD

**Issue by russelltankl** [chainer/chainerrl#523]
Hello,

I'm trying to load two trained models for inference simultaneously in a single inference loop.
```
first_agent = PPO(first_param)
second_agent = PPO(second_param)

first_agent.load(first_weight)
second_agent.load(second_weight)

for i in range(N):
    obs = env.reset()
    ...
    while not done and t < T:
        env.render()
        action = first_agent.act(obs)
        something = second_agent(obs)
``` 

By observation of the rendered environment, it seems like the second agent's weights are properly loaded while the first agent's weights are overwritten. Hence if I simply swap the loading sequence, the first agent's weights will be properly loaded instead of the second agent's.

Is there a way to properly load both agents in this scenario?

Thanks

**Comment by ummavi** [comment]
Could you please expand on `first_param` and `second_param` when you're initializing the agents?

Specifically, are you passing both PPO agents separate models?

**Comment by russelltankl** [comment]
My mistake is not specifically defining two separate models, it works fine now. Thanks!
