### ISSUE TITLE
Add trained models

### ISSUE THREAD

**Issue by prabhatnagarajan** [chainer/chainerrl#551]
- Add an example where a user can load a trained model.

**Comment by Pit-Storm** [comment]
There are trained Models now, but one is not able to download it. If I run the reproduction example for A3C with pretrained model demo, I got a HTTP Error "403: Forbidden" for the URL  https://chainer-assets.preferred.jp/chainerrl/A3C/Breakout\final.zip

I think this is a convenience with joining paths. Are you joining the URL-Path with os.path.join?
When it's coming to on-disk-paths python can handle \ or / in whatever OS it is. On windows os.path.join joins with \ and on unix systems it joins with /. When you join a URL on windows it joins a \ instead a /.

When i replace the \ (right before final.zip in the upper URL) with an / I can access the file manually.

Maybe you can fix it in your code?

**Comment by prabhatnagarajan** [comment]
You're correct that we use join: https://github.com/chainer/chainerrl/blob/master/chainerrl/misc/pretrained_models.py#L124
`cache_path = cached_download(os.path.join(url_basepath,file))`
Where `file` is `final.zip`. 

Thanks for sharing! I'll try and amend this.
