### ISSUE TITLE
Bug in Soft Actor Critic's batch_observe_and_train

### ISSUE THREAD

**Issue by ummavi** [chainer/chainerrl#557]
`env_id` is not passed as a parameter when transitions are added to the replay buffer in Soft Actor Critic.

https://github.com/chainer/chainerrl/blob/8bee9da793bffa352e1d2c2fba16b4f148ba0253/chainerrl/agents/soft_actor_critic.py#L377

**Comment by prabhatnagarajan** [comment]
Look at this PR as a reference: https://github.com/chainer/chainerrl/pull/442/files

**Comment by ummavi** [comment]
Resolved by #558
