### ISSUE TITLE
Saving models at timestamps

### ISSUE THREAD

**Issue by Ujwal2910** [chainer/chainerrl#586]
I am using the train_ppo_gym script and the problem with this script is that it does not save model when the training crashes or is closed for some reason.
Earlier with a3c i used to get 10_except as saved model in case i wanted to stop the training.
I want to save mdoels for evey 100th step or episode. Could you please provide an update on this behavior?

**Comment by prabhatnagarajan** [comment]
> I am using the train_ppo_gym script and the problem with this script is that it does not save model when the training crashes or is closed for some reason.
Could you clarify this?

We have functionality that can checkpoint models periodically, though it has not been implemented for `train_ppo_gym`.  Checkout the `train_ppo_ale.py` example: https://github.com/chainer/chainerrl/blob/master/examples/atari/train_ppo_ale.py#L87

**Comment by prabhatnagarajan** [comment]
Does this answer your question?

**Comment by Ujwal2910** [comment]
Yeah this works. Just one more question is that whether any of the train_ppo files have used LSTM networks?

**Comment by prabhatnagarajan** [comment]
Checkout https://github.com/chainer/chainerrl/blob/master/examples/atari/train_ppo_ale.py#L131. Not LSTMS, but GRUs.
