### ISSUE TITLE
What do 'agent.save' mean??

### ISSUE THREAD

**Issue by KitanoFumiya** [chainer/chainerrl#588]
I am doing reinforcement learning using MujoCo. The policy model was implemented using Gaussian policies. I also use TRPO. "Obs_normalizer.npz", "policy.npz", "vf.npz", "vf_optimizer.npz" were saved in agent.save. However, when you look at the data inside, you don't know what they represent. I want to reproduce Gaussian multivariate normal distribution. Can I duplicate using stored data? If you like, please let me know the sample code.

**Comment by muupan** [comment]
`agent.save` will save the parameters of the models (`obs_normalizer`, `policy`, and `vf` for TRPO) and the optimizer' state (`vf_optimizer.npz`). These files are generated using Chainer's serialization functions: `chainer.serializers.save_npz` and `chainer.serializers.load_npz`: https://docs.chainer.org/en/stable/reference/serializers.html

To load the saved files, you can call `agent.load` with the path to the directory where those files were saved. You can check how `--load` option is used in examples: https://github.com/chainer/chainerrl/blob/master/examples/mujoco/reproduction/trpo/train_trpo.py#L153

**Comment by KitanoFumiya** [comment]
> 
> 
> `agent.save` will save the parameters of the models (`obs_normalizer`, `policy`, and `vf` for TRPO) and the optimizer' state (`vf_optimizer.npz`). These files are generated using Chainer's serialization functions: `chainer.serializers.save_npz` and `chainer.serializers.load_npz`: https://docs.chainer.org/en/stable/reference/serializers.html
> 
> To load the saved files, you can call `agent.load` with the path to the directory where those files were saved. You can check how `--load` option is used in examples: https://github.com/chainer/chainerrl/blob/master/examples/mujoco/reproduction/trpo/train_trpo.py#L153

Thank you!
I could load these data.
I want to draw a multidimensional normal distribution using these data. Is that possible?

**Comment by muupan** [comment]
What do you mean by "draw a multidimensional normal distribution"? If you want to know the shape of the action distribution for a given state, you can check the output of `policy`. It returns  a `GaussianDistribution` object (https://github.com/chainer/chainerrl/blob/master/chainerrl/distribution.py#L275) where you can check its mean and variance manually.

**Comment by KitanoFumiya** [comment]
Thank you very much！.
 Can I tell me a program to get the average and variance of the policy if you like?

**Comment by KitanoFumiya** [comment]
> 
> 
> What do you mean by "draw a multidimensional normal distribution"? If you want to know the shape of the action distribution for a given state, you can check the output of `policy`. It returns a `GaussianDistribution` object (https://github.com/chainer/chainerrl/blob/master/chainerrl/distribution.py#L275) where you can check its mean and variance manually.

Thank you very much. Can I tell me a program to get the average and variance of the policy if you like?

**Comment by muupan** [comment]
> Can I tell me a program to get the average and variance of the policy if you like?

You can access these attributes. https://github.com/chainer/chainerrl/blob/018a29132d77e5af0f92161250c72aba10c6ce29/chainerrl/distribution.py#L279-L280
