### ISSUE TITLE
Tensorboard support

### ISSUE THREAD

**Issue by Ujwal2910** [chainer/chainerrl#597]
Is there a tensorboard like support in ChainerRL?

**Comment by prabhatnagarajan** [comment]
Sorry for the late response. ChainerRL doesn't have tensorboard support, but our PyTorch version of ChainerRL (PFRL), has Tensorboard support. If you would like to adapt it for ChainerRL, see this PR in PFRL: https://github.com/pfnet/pfrl/pull/12.

**Comment by prabhatnagarajan** [comment]
Closing this issue, please open re-open if my response was unclear or there are followup questions.
