### ISSUE TITLE
(How to) Provide a random agent for evaluation

### ISSUE THREAD

**Issue by Pit-Storm** [chainer/chainerrl#599]
Dear maintainers,

for various research it would be great to have a random Agent/Model at hand to evaluate the model one created.

Is it possible that you can provide a random agent or a code snippet to create one in self-service?

Great work and kind regards!

**Comment by muupan** [comment]
A simple way is just follow the code example on the OpenAI Gym website: https://gym.openai.com/

If you want to reuse evaluation code for ChainerRL agents, for discrete-action envs, `chainerrl.wrappers.RandomizeAction` can be used to simulate a uniform random policy. It is used in https://github.com/chainer/chainerrl/blob/master/examples/atari/reproduction/dqn/train_dqn.py#L78.  The wrapper does not support continuous actions, but you can write a similar wrapper.
