### ISSUE TITLE
Type of observation and action space

### ISSUE THREAD

**Issue by longjie** [chainer/chainerrl#66]
I think the examples of gym interface show, the agent and q_functions expect the observation and action to be a Box or a Discrete for each. Is it correct?

If so, how should I use the observation and action other typed, especially a Tuple?
Do I need to modify the environment as to return a Box, or do I have another choice?

Thanks,

**Comment by muupan** [comment]
There was some discussion on this issue on chainer-jp's slack. I paste it for everyone's information.
```
Ryosuke Tajima [6:45 AM] 
こんばんは。
https://github.com/pfnet/chainerrl/issues/66 issueを出してしまったのですが、chainerrlでgym/Boxとgym/Discrete以外の、例えばgym/Tupleをobservationとactionにしたい場合はどうするのが良いのでしょうか？ q_functionはそれ用に自分で書くのかなと思いますが、agentも自分で修正する必要があるのでしょうか？ (edited)

tos [11:38 AM] 
こんばんは。
agentを修正しないでできる方法はいくつかありそうです。
学習したい環境のobservationがBoxのobservationに変換できる場合は，いくつかのagentに引数
phi (callable): Feature extractor applied to observations
が実装されていて，それが使えることがあります。
actionについても，BoxやDiscreteから変換できるactionにしてしまって十分な場合はchainerrl.misc.env_modifierを使うことができます。
一方，Tupleのactionをちゃんと扱うには，たとえばDQNで学習させる場合，q_functionの戻り値のclass（chainerrl.action_value.ActionValueのsubclassにする）まで自分で書けばできそうに思います。

Ryosuke Tajima [7:39 PM] 
ありがとうございます、助かります。phiとenv_modifierを使うことを検討してみます。gymの環境の定義をyamlとかの設定ファイルで可変にしたものをchainerrlで学習させるというのができないかと思っています。Dict Spaceなんてのも作ってPR送ったのですが(https://github.com/openai/gym/pull/563)、なかなか難しそうなのでTupleでもいいから構造化されたデータを扱えればと思いました。またよろしくおねがいします。
```

**Comment by muupan** [comment]
To summarize,
- You can specify `phi` to agents to extract features from any observation_space.
- Supporting non-Box, non-Discrete action_space is not straightforward for now. You have to convert it into Box or Discrete, or you need to extend `chainerrl.action_value.ActionValue`.
