### ISSUE TITLE
PyTorch as an additional backend

### ISSUE THREAD

**Issue by muupan** [chainer/chainerrl#73]
I'm curious about whether ChainerRL can support PyTorch as an additional NN backend. Its interface is similar to Chainer's, but I'm not sure how easy it would be to support both. Any suggestions and opinions are welcome.

**Comment by ethancaballero** [comment]
cc: @jekbradbury

**Comment by prabhatnagarajan** [comment]
We have migrated ChainerRL to PFRL(https://github.com/pfnet/pfrl), which is a PyTorch-based analog of ChainerRL. As such, we won't be adding additional support in this repository for a PyTorch backend.
